[package]
name = "lumen"
version = "0.1.0"
edition = "2021"

[dependencies]
gpui = { git = "https://github.com/zed-industries/zed" }
quickraw = { version = "0.1.6", features = ["image"] }
rfd = "0.15.2"
sha2 = "0.10.8"
